const maps = [
	{ id: 0, name: 'Mao Kun', tier: 8, upgradesFrom: [], pantheon: false, pantheonText: '', unique: true },
	{ id: 1, name: 'Pit of the Chimera', tier: 16, upgradesFrom: [{id: 10, name: 'Lava Lake'}, {id: 12, name: 'Desert Spring'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 2, name: 'Lair of the Hydra', tier: 16, upgradesFrom: [{id: 9, name: 'Tower'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 3, name: 'Maze of the Minotaur', tier: 16, upgradesFrom: [{id: 7, name: 'Primordial Blocks'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 4, name: 'Forge of the Phoenix', tier: 16, upgradesFrom: [{id: 8, name: 'Summit'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 5, name: 'The Shaper\'s Realm', tier: 17, upgradesFrom: [], pantheon: false, pantheonText: '', unique: false },
	{ id: 6, name: 'Carcass', tier: 14, upgradesFrom: [{id: 21, name: 'Shrine'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 7, name: 'Primordial Blocks', tier: 15, upgradesFrom: [{id: 129, name: 'Courthouse'}, {id: 6, name: 'Carcass'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 8, name: 'Summit', tier: 15, upgradesFrom: [{id: 23, name: 'Terrace'}], pantheon: true, pantheonText: 'Captured Soul of Mephod, the Earth Scorcher', unique: false },
	{ id: 9, name: 'Tower', tier: 15, upgradesFrom: [{id: 15, name: 'Dark Forest'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 10, name: 'Lava Lake', tier: 15, upgradesFrom: [{id: 16, name: 'Basilica'}, {id: 18, name: 'Sunken City'}, {id: 11, name: 'Palace'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 11, name: 'Palace', tier: 14, upgradesFrom: [{id: 31, name: 'Racecourse'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 12, name: 'Desert Spring', tier: 15, upgradesFrom: [{id: 11, name: 'Palace'}], pantheon: true, pantheonText: 'Captured Soul of Terror of the Infinite Drifts', unique: false },
	{ id: 13, name: 'Vaal Temple', tier: 16, upgradesFrom: [], pantheon: false, pantheonText: '', unique: false },
	{ id: 14, name: 'Plaza', tier: 10, upgradesFrom: [{id: 114, name: 'Ancient City'}, {id: 132, name: 'Relic Chambers'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 15, name: 'Dark Forest', tier: 14, upgradesFrom: [{id: 19, name: 'Core'}, {id: 42, name: 'Acid Caverns'}, {id: 32, name: 'Reef'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 16, name: 'Basilica', tier: 14, upgradesFrom: [{id: 29, name: 'Caldera'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 17, name: 'Crimson Temple', tier: 13, upgradesFrom: [{id: 35, name: 'Castle Ruins'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 18, name: 'Sunken City', tier: 14, upgradesFrom: [{id: 29, name: 'Caldera'}], pantheon: true, pantheonText: 'Captured Soul of Armala, the Widow', unique: false },
	{ id: 19, name: 'Core', tier: 13, upgradesFrom: [{id: 47, name: 'Colonnade'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 20, name: 'Dig', tier: 13, upgradesFrom: [{id: 113, name: 'Ivory Temple'}], pantheon: true, pantheonText: 'Captured Soul of Stalker of the Endless Dunes', unique: false },
	{ id: 21, name: 'Shrine', tier: 13, upgradesFrom: [{id: 37, name: 'Overgrown Shrine'}, {id: 22, name: 'Arsenal'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 22, name: 'Arsenal', tier: 12, upgradesFrom: [{id: 55, name: 'Bog'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 23, name: 'Terrace', tier: 14, upgradesFrom: [{id: 20, name: 'Dig'}, {id: 17, name: 'Crimson Temple'}], pantheon: true, pantheonText: 'Captured Soul of Varhesh, Shimmering Aberration', unique: false },
	{ id: 24, name: 'Malformation', tier: 12, upgradesFrom: [{id: 60, name: 'Siege'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 25, name: 'Death and Taxes', tier: 12, upgradesFrom: [], pantheon: false, pantheonText: '', unique: true },
	{ id: 26, name: 'Oba\'s Cursed Trove', tier: 5, upgradesFrom: [], pantheon: false, pantheonText: '', unique: true },
	{ id: 27, name: 'Park', tier: 11, upgradesFrom: [{id: 39, name: 'Pit'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 28, name: 'Ghetto', tier: 7, upgradesFrom: [{id: 123, name: 'Canyon'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 29, name: 'Caldera', tier: 13, upgradesFrom: [{id: 38, name: 'Defiled Cathedral'}], pantheon: true, pantheonText: 'Captured Soul of The Infernal King', unique: false },
	{ id: 30, name: 'Necropolis', tier: 12, upgradesFrom: [{id: 136, name: 'Burial Chambers'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 31, name: 'Racecourse', tier: 13, upgradesFrom: [{id: 30, name: 'Necropolis'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 32, name: 'Reef', tier: 13, upgradesFrom: [{id: 33, name: 'Villa'}], pantheon: true, pantheonText: 'Captured Soul of Nassar, Lion of the Seas', unique: false },
	{ id: 33, name: 'Villa', tier: 12, upgradesFrom: [{id: 58, name: 'Arachnid Tomb'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 34, name: 'Crystal Ore', tier: 11, upgradesFrom: [{id: 101, name: 'Coral Ruins'}, {id: 139, name: 'Leyline'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 35, name: 'Castle Ruins', tier: 12, upgradesFrom: [{id: 48, name: 'Lair'}, {id: 131, name: 'Chateau'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 36, name: 'Acton\'s Nightmare', tier: 12, upgradesFrom: [], pantheon: false, pantheonText: '', unique: true },
	{ id: 37, name: 'Overgrown Shrine', tier: 12, upgradesFrom: [{id: 55, name: 'Bog'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 38, name: 'Defiled Cathedral', tier: 12, upgradesFrom: [{id: 27, name: 'Park'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 39, name: 'Pit', tier: 10, upgradesFrom: [{id: 75, name: 'Moon Temple'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 40, name: 'Mesa', tier: 11, upgradesFrom: [{id: 139, name: 'Leyline'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 41, name: 'Colosseum', tier: 13, upgradesFrom: [{id: 24, name: 'Malformation'}], pantheon: true, pantheonText: 'Captured Soul of Ambrius, Legion Slayer', unique: false },
	{ id: 42, name: 'Acid Caverns', tier: 13, upgradesFrom: [{id: 33, name: 'Villa'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 43, name: 'Factory', tier: 11, upgradesFrom: [{id: 54, name: 'Pier'}, {id: 44, name: 'Spider Forest'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 44, name: 'Spider Forest', tier: 10, upgradesFrom: [{id: 71, name: 'Waste Pool'}, {id: 77, name: 'Tropical Island'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 45, name: 'Coves', tier: 10, upgradesFrom: [{id: 68, name: 'Vault'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 46, name: 'Primordial Pool', tier: 7, upgradesFrom: [{id: 107, name: 'Ashen Wood'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 47, name: 'Colonnade', tier: 12, upgradesFrom: [{id: 40, name: 'Mesa'}, {id: 34, name: 'Crystal Ore'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 48, name: 'Lair', tier: 11, upgradesFrom: [{id: 69, name: 'Estuary'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 49, name: 'The Hall of Grandmasters', tier: 8, upgradesFrom: [], pantheon: false, pantheonText: '', unique: true },
	{ id: 50, name: 'Promenade', tier: 8, upgradesFrom: [{id: 46, name: 'Primordial Pool'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 51, name: 'Orchard', tier: 8, upgradesFrom: [{id: 97, name: 'Dunes'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 52, name: 'The Coward\'s Trial', tier: 3, upgradesFrom: [], pantheon: false, pantheonText: '', unique: true },
	{ id: 53, name: 'Cursed Crypt', tier: 3, upgradesFrom: [{id: 143, name: 'Iceberg'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 54, name: 'Pier', tier: 10, upgradesFrom: [{id: 67, name: 'Cemetery'}, {id: 71, name: 'Waste Pool'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 55, name: 'Bog', tier: 11, upgradesFrom: [{id: 70, name: 'Plateau'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 56, name: 'Precinct', tier: 6, upgradesFrom: [{id: 155, name: 'Jungle Valley'}, {id: 112, name: 'Mausoleum'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 57, name: 'Wasteland', tier: 8, upgradesFrom: [{id: 28, name: 'Ghetto'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 58, name: 'Arachnid Tomb', tier: 11, upgradesFrom: [{id: 59, name: 'Belfry'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 59, name: 'Belfry', tier: 10, upgradesFrom: [{id: 72, name: 'Waterways'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 60, name: 'Siege', tier: 11, upgradesFrom: [{id: 14, name: 'Plaza'}], pantheon: true, pantheonText: 'Captured Soul of Tahsin, Warmaker', unique: false },
	{ id: 61, name: 'Scriptorium', tier: 9, upgradesFrom: [{id: 79, name: 'Mud Geyser'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 62, name: 'Shipyard', tier: 3, upgradesFrom: [{id: 150, name: 'Dungeon'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 63, name: 'The Putrid Cloister', tier: 9, upgradesFrom: [], pantheon: false, pantheonText: '', unique: true },
	{ id: 64, name: 'Museum', tier: 9, upgradesFrom: [{id: 76, name: 'Mineral Pools'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 65, name: 'Arena', tier: 9, upgradesFrom: [{id: 73, name: 'Sepulchre'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 66, name: 'Hallowed Ground', tier: 9, upgradesFrom: [], pantheon: false, pantheonText: '', unique: true },
	{ id: 67, name: 'Cemetery', tier: 9, upgradesFrom: [{id: 57, name: 'Wasteland'}], pantheon: true, pantheonText: 'Captured Soul of Erebix, Light\'s Bane', unique: false },
	{ id: 68, name: 'Vault', tier: 9, upgradesFrom: [{id: 50, name: 'Promenade'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 69, name: 'Estuary', tier: 10, upgradesFrom: [{id: 77, name: 'Tropical Island'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 70, name: 'Plateau', tier: 10, upgradesFrom: [{id: 61, name: 'Scriptorium'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 71, name: 'Waste Pool', tier: 9, upgradesFrom: [{id: 51, name: 'Orchard'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 72, name: 'Waterways', tier: 9, upgradesFrom: [{id: 86, name: 'Overgrown Ruin'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 73, name: 'Sepulchre', tier: 8, upgradesFrom: [{id: 122, name: 'Conservatory'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 74, name: 'The Twilight Temple', tier: 9, upgradesFrom: [], pantheon: false, pantheonText: '', unique: true },
	{ id: 75, name: 'Moon Temple', tier: 9, upgradesFrom: [{id: 88, name: 'Laboratory'}], pantheon: true, pantheonText: 'Captured Soul of Sebbert, Crescent\'s Point', unique: false },
	{ id: 76, name: 'Mineral Pools', tier: 8, upgradesFrom: [{id: 83, name: 'Geode'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 77, name: 'Tropical Island', tier: 9, upgradesFrom: [{id: 87, name: 'Infested Valley'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 78, name: 'Shore', tier: 8, upgradesFrom: [{id: 89, name: 'Bazaar'}], pantheon: true, pantheonText: 'Captured Soul of Belcer, the Pirate Lord', unique: false },
	{ id: 79, name: 'Mud Geyser', tier: 8, upgradesFrom: [{id: 115, name: 'Toxic Sewer'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 80, name: 'The Vinktar Square', tier: 4, upgradesFrom: [], pantheon: false, pantheonText: '', unique: true },
	{ id: 81, name: 'Courtyard', tier: 4, upgradesFrom: [{id: 138, name: 'Peninsula'}, {id: 62, name: 'Shipyard'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 82, name: 'Armoury', tier: 2, upgradesFrom: [{id: 119, name: 'Channel'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 83, name: 'Geode', tier: 7, upgradesFrom: [{id: 120, name: 'Sulphur Vents'}, {id: 56, name: 'Precinct'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 84, name: 'Vaults of Atziri', tier: 5, upgradesFrom: [], pantheon: false, pantheonText: '', unique: true },
	{ id: 85, name: 'Vaal Pyramid', tier: 5, upgradesFrom: [{id: 110, name: 'Barrows'}, {id: 153, name: 'Beach'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 86, name: 'Overgrown Ruin', tier: 8, upgradesFrom: [{id: 100, name: 'Lava Chamber'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 87, name: 'Infested Valley', tier: 8, upgradesFrom: [{id: 97, name: 'Dunes'}], pantheon: true, pantheonText: 'Captured Soul of Gorulis, Will-Thief', unique: false },
	{ id: 88, name: 'Laboratory', tier: 8, upgradesFrom: [{id: 102, name: 'Cells'}, {id: 93, name: 'Underground River'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 89, name: 'Bazaar', tier: 7, upgradesFrom: [{id: 156, name: 'Phantasmagoria'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 90, name: 'Arachnid Nest', tier: 8, upgradesFrom: [{id: 134, name: 'Arcade'}, {id: 89, name: 'Bazaar'}], pantheon: true, pantheonText: 'Captured Soul of Spinner of False Hope', unique: false },
	{ id: 91, name: 'Gardens', tier: 5, upgradesFrom: [{id: 81, name: 'Courtyard'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 92, name: 'Caer Blaidd, Wolfpack\'s Den', tier: 7, upgradesFrom: [], pantheon: false, pantheonText: '', unique: true },
	{ id: 93, name: 'Underground River', tier: 7, upgradesFrom: [{id: 157, name: 'Academy'}, {id: 118, name: 'Haunted Mansion'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 94, name: 'Olmec\'s Sanctum', tier: 3, upgradesFrom: [], pantheon: false, pantheonText: '', unique: true },
	{ id: 95, name: 'Bone Crypt', tier: 3, upgradesFrom: [{id: 148, name: 'Pen'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 96, name: 'Pillars of Arun', tier: 7, upgradesFrom: [], pantheon: false, pantheonText: '', unique: true },
	{ id: 97, name: 'Dunes', tier: 7, upgradesFrom: [{id: 121, name: 'Fields'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 98, name: 'Ramparts', tier: 1, upgradesFrom: [], pantheon: false, pantheonText: '', unique: false },
	{ id: 99, name: 'Residence', tier: 5, upgradesFrom: [{id: 154, name: 'Lookout'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 100, name: 'Lava Chamber', tier: 7, upgradesFrom: [{id: 125, name: 'Volcano'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 101, name: 'Coral Ruins', tier: 10, upgradesFrom: [{id: 64, name: 'Museum'}, {id: 65, name: 'Arena'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 102, name: 'Cells', tier: 7, upgradesFrom: [{id: 118, name: 'Haunted Mansion'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 103, name: 'Underground Sea', tier: 5, upgradesFrom: [{id: 144, name: 'Marshes'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 104, name: 'Poorjoy\'s Asylum', tier: 6, upgradesFrom: [], pantheon: false, pantheonText: '', unique: true },
	{ id: 105, name: 'Temple', tier: 6, upgradesFrom: [{id: 99, name: 'Residence'}], pantheon: true, pantheonText: 'Captured Soul of Jorus, Sky\'s Edge', unique: false },
	{ id: 106, name: 'Maelström of Chaos', tier: 1, upgradesFrom: [], pantheon: false, pantheonText: '', unique: true },
	{ id: 107, name: 'Ashen Wood', tier: 6, upgradesFrom: [{id: 149, name: 'Alleyways'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 108, name: 'Atoll', tier: 1, upgradesFrom: [], pantheon: false, pantheonText: '', unique: false },
	{ id: 109, name: 'Thicket', tier: 2, upgradesFrom: [{id: 119, name: 'Channel'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 110, name: 'Barrows', tier: 4, upgradesFrom: [{id: 95, name: 'Bone Crypt'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 111, name: 'Spider Lair', tier: 4, upgradesFrom: [{id: 147, name: 'Desert'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 112, name: 'Mausoleum', tier: 5, upgradesFrom: [{id: 135, name: 'Crater'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 113, name: 'Ivory Temple', tier: 12, upgradesFrom: [{id: 43, name: 'Factory'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 114, name: 'Ancient City', tier: 9, upgradesFrom: [{id: 90, name: 'Arachnid Nest'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 115, name: 'Toxic Sewer', tier: 7, upgradesFrom: [{id: 158, name: 'Wharf'}, {id: 105, name: 'Temple'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 116, name: 'Doryani\'s Machinarium', tier: 5, upgradesFrom: [], pantheon: false, pantheonText: '', unique: true },
	{ id: 117, name: 'Maze', tier: 5, upgradesFrom: [{id: 130, name: 'Strand'}, {id: 111, name: 'Spider Lair'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 118, name: 'Haunted Mansion', tier: 6, upgradesFrom: [{id: 137, name: 'Port'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 119, name: 'Channel', tier: 1, upgradesFrom: [], pantheon: false, pantheonText: '', unique: false },
	{ id: 120, name: 'Sulphur Vents', tier: 6, upgradesFrom: [{id: 112, name: 'Mausoleum'}], pantheon: true, pantheonText: 'Captured Soul of The Gorgon', unique: false },
	{ id: 121, name: 'Fields', tier: 6, upgradesFrom: [{id: 133, name: 'City Square'}], pantheon: true, pantheonText: 'Captured Soul of Drek, Apex Hunter', unique: false },
	{ id: 122, name: 'Conservatory', tier: 7, upgradesFrom: [{id: 56, name: 'Precinct'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 123, name: 'Canyon', tier: 6, upgradesFrom: [{id: 85, name: 'Vaal Pyramid'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 124, name: 'Lighthouse', tier: 4, upgradesFrom: [{id: 152, name: 'Grotto'}, {id: 141, name: 'Fungal Hollow'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 125, name: 'Volcano', tier: 6, upgradesFrom: [{id: 103, name: 'Underground Sea'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 126, name: 'Glacier', tier: 4, upgradesFrom: [{id: 151, name: 'Graveyard'}, {id: 140, name: 'Excavation'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 127, name: 'Perandus Manor', tier: 11, upgradesFrom: [], pantheon: false, pantheonText: '', unique: true },
	{ id: 128, name: 'Whakawairua Tuahu', tier: 4, upgradesFrom: [], pantheon: false, pantheonText: '', unique: true },
	{ id: 129, name: 'Courthouse', tier: 14, upgradesFrom: [{id: 41, name: 'Colosseum'}, {id: 21, name: 'Shrine'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 130, name: 'Strand', tier: 4, upgradesFrom: [{id: 140, name: 'Excavation'}, {id: 147, name: 'Desert'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 131, name: 'Chateau', tier: 11, upgradesFrom: [{id: 44, name: 'Spider Forest'}, {id: 69, name: 'Estuary'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 132, name: 'Relic Chambers', tier: 9, upgradesFrom: [{id: 78, name: 'Shore'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 133, name: 'City Square', tier: 5, upgradesFrom: [{id: 153, name: 'Beach'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 134, name: 'Arcade', tier: 7, upgradesFrom: [{id: 105, name: 'Temple'}, {id: 156, name: 'Phantasmagoria'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 135, name: 'Crater', tier: 4, upgradesFrom: [{id: 53, name: 'Cursed Crypt'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 136, name: 'Burial Chambers', tier: 11, upgradesFrom: [{id: 45, name: 'Coves'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 137, name: 'Port', tier: 5, upgradesFrom: [{id: 111, name: 'Spider Lair'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 138, name: 'Peninsula', tier: 3, upgradesFrom: [{id: 150, name: 'Dungeon'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 139, name: 'Leyline', tier: 10, upgradesFrom: [{id: 65, name: 'Arena'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 140, name: 'Excavation', tier: 3, upgradesFrom: [{id: 82, name: 'Armoury'}, {id: 109, name: 'Thicket'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 141, name: 'Fungal Hollow', tier: 3, upgradesFrom: [{id: 146, name: 'Arid Lake'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 142, name: 'Cage', tier: 3, upgradesFrom: [{id: 148, name: 'Pen'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 143, name: 'Iceberg', tier: 2, upgradesFrom: [{id: 108, name: 'Atoll'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 144, name: 'Marshes', tier: 4, upgradesFrom: [{id: 141, name: 'Fungal Hollow'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 145, name: 'Flooded Mine', tier: 1, upgradesFrom: [], pantheon: false, pantheonText: '', unique: false },
	{ id: 146, name: 'Arid Lake', tier: 2, upgradesFrom: [{id: 108, name: 'Atoll'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 147, name: 'Desert', tier: 3, upgradesFrom: [{id: 109, name: 'Thicket'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 148, name: 'Pen', tier: 2, upgradesFrom: [{id: 98, name: 'Ramparts'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 149, name: 'Alleyways', tier: 5, upgradesFrom: [{id: 126, name: 'Glacier'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 150, name: 'Dungeon', tier: 2, upgradesFrom: [{id: 145, name: 'Flooded Mine'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 151, name: 'Graveyard', tier: 3, upgradesFrom: [{id: 82, name: 'Armoury'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 152, name: 'Grotto', tier: 3, upgradesFrom: [{id: 143, name: 'Iceberg'}, {id: 146, name: 'Arid Lake'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 153, name: 'Beach', tier: 4, upgradesFrom: [{id: 142, name: 'Cage'}, {id: 95, name: 'Bone Crypt'}], pantheon: true, pantheonText: 'Captured Soul of Glace', unique: false },
	{ id: 154, name: 'Lookout', tier: 4, upgradesFrom: [{id: 62, name: 'Shipyard'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 155, name: 'Jungle Valley', tier: 5, upgradesFrom: [{id: 124, name: 'Lighthouse'}, {id: 144, name: 'Marshes'}, {id: 135, name: 'Crater'}], pantheon: true, pantheonText: 'Captured Soul of Queen of the Great Tangle', unique: false },
	{ id: 156, name: 'Phantasmagoria', tier: 6, upgradesFrom: [{id: 99, name: 'Residence'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 157, name: 'Academy', tier: 6, upgradesFrom: [{id: 117, name: 'Maze'}, {id: 137, name: 'Port'}], pantheon: false, pantheonText: '', unique: false },
	{ id: 158, name: 'Wharf', tier: 6, upgradesFrom: [{id: 91, name: 'Gardens'}], pantheon: true, pantheonText: 'Captured Soul of Stone of the Currents', unique: false },
];

export default maps;
