const maps = [
  { id: 0, name: 'Atoll', tier: 1, upgradesFrom: [], upgradesTo: ['Arid Lake', 'Iceberg'], isUnique: false },
  { id: 1, name: 'Channel', tier: 1, upgradesFrom: [], upgradesTo: ['Armoury', 'Thicket'], isUnique: false },
  { id: 2, name: 'Flooded Mine', tier: 1, upgradesFrom: [], upgradesTo: ['Dungeon'], isUnique: false },
  { id: 3, name: 'Ramparts', tier: 1, upgradesFrom: [], upgradesTo: ['Pen'], isUnique: false },
  { id: 4, name: 'Arid Lake', tier: 2, upgradesFrom: ['Atoll'], upgradesTo: ['Fungal Hollow', 'Grotto'], isUnique: false },
  { id: 5, name: 'Iceberg', tier: 2, upgradesFrom: ['Atoll'], upgradesTo: ['Grotto', 'Cursed Crypt'], isUnique: false },
  { id: 6, name: 'Armoury', tier: 2, upgradesFrom: ['Channel'], upgradesTo: ['Graveyard', 'Excavation'], isUnique: false },
  { id: 7, name: 'Thicket', tier: 2, upgradesFrom: ['Channel'], upgradesTo: ['Desert', 'Excavation'], isUnique: false },
  { id: 8, name: 'Dungeon', tier: 2, upgradesFrom: ['Flooded Mine'], upgradesTo: ['Shipyard', 'Peninsula'], isUnique: false },
  { id: 9, name: 'Pen', tier: 2, upgradesFrom: ['Ramparts'], upgradesTo: ['Bone Crypt', 'Cage'], isUnique: false },
  { id: 10, name: 'Fungal Hollow', tier: 3, upgradesFrom: ['Arid Lake'], upgradesTo: ['Marshes', 'Lighthouse'], isUnique: false },
  { id: 11, name: 'Grotto', tier: 3, upgradesFrom: ['Arid Lake', 'Iceberg'], upgradesTo: ['Lighthouse'], isUnique: false },
  { id: 12, name: 'Cursed Crypt', tier: 3, upgradesFrom: ['Iceberg'], upgradesTo: ['Crater'], isUnique: false },
  { id: 13, name: 'Graveyard', tier: 3, upgradesFrom: ['Armoury'], upgradesTo: ['Glacier'], isUnique: false },
  { id: 14, name: 'Excavation', tier: 3, upgradesFrom: ['Armoury', 'Thicket'], upgradesTo: ['Glacier', 'Strand'], isUnique: false },
  { id: 15, name: 'Desert', tier: 3, upgradesFrom: ['Thicket'], upgradesTo: ['Spider Lair', 'Strand'], isUnique: false },
  { id: 16, name: 'Shipyard', tier: 3, upgradesFrom: ['Dungeon'], upgradesTo: ['Lookout', 'Courtyard'], isUnique: false },
  { id: 17, name: 'Peninsula', tier: 3, upgradesFrom: ['Dungeon'], upgradesTo: ['Courtyard'], isUnique: false },
  { id: 18, name: 'Bone Crypt', tier: 3, upgradesFrom: ['Pen'], upgradesTo: ['Barrows', 'Beach'], isUnique: false },
  { id: 19, name: 'Cage', tier: 3, upgradesFrom: ['Pen'], upgradesTo: ['Beach'], isUnique: false },
  { id: 20, name: 'Marshes', tier: 4, upgradesFrom: ['Fungal Hollow'], upgradesTo: ['Underground Sea', 'Jungle Valley'], isUnique: false },
  { id: 21, name: 'Lighthouse', tier: 4, upgradesFrom: ['Fungal Hollow', 'Grotto'], upgradesTo: ['Jungle Valley'], isUnique: false },
  { id: 22, name: 'Crater', tier: 4, upgradesFrom: ['Cursed Crypt'], upgradesTo: ['Jungle Valley', 'Mausoleum'], isUnique: false },
  { id: 23, name: 'Glacier', tier: 4, upgradesFrom: ['Graveyard', 'Excavation'], upgradesTo: ['Alleyways'], isUnique: false },
  { id: 24, name: 'Strand', tier: 4, upgradesFrom: ['Desert', 'Excavation'], upgradesTo: ['Maze'], isUnique: false },
  { id: 25, name: 'Spider Lair', tier: 4, upgradesFrom: ['Desert'], upgradesTo: ['Maze', 'Port'], isUnique: false },
  { id: 26, name: 'Lookout', tier: 4, upgradesFrom: ['Shipyard'], upgradesTo: ['Residence'], isUnique: false },
  { id: 27, name: 'Courtyard', tier: 4, upgradesFrom: ['Shipyard', 'Peninsula'], upgradesTo: ['Gardens'], isUnique: false },
  { id: 28, name: 'Barrows', tier: 4, upgradesFrom: ['Bone Crypt'], upgradesTo: ['Vaal Pyramid'], isUnique: false },
  { id: 29, name: 'Beach', tier: 4, upgradesFrom: ['Bone Crypt', 'Cage'], upgradesTo: ['Vaal Pyramid', 'City Square'], isUnique: false },
  { id: 30, name: 'Underground Sea', tier: 5, upgradesFrom: ['Marshes'], upgradesTo: ['Volcano'], isUnique: false },
  { id: 31, name: 'Jungle Valley', tier: 5, upgradesFrom: ['Marshes', 'Crater'], upgradesTo: ['Precinct'], isUnique: false },
  { id: 32, name: 'Mausoleum', tier: 5, upgradesFrom: ['Crater'], upgradesTo: ['Precinct', 'Sulphur Vents'], isUnique: false },
  { id: 33, name: 'Alleyways', tier: 5, upgradesFrom: ['Glacier'], upgradesTo: ['Ashen Wood'], isUnique: false },
  { id: 34, name: 'Maze', tier: 5, upgradesFrom: ['Strand', 'Spider Lair'], upgradesTo: ['Academy'], isUnique: false },
  { id: 35, name: 'Port', tier: 5, upgradesFrom: ['Spider Lair'], upgradesTo: ['Academy', 'Haunted Mansion'], isUnique: false },
  { id: 36, name: 'Residence', tier: 5, upgradesFrom: ['Lookout'], upgradesTo: ['Phantasmagoria', 'Temple'], isUnique: false },
  { id: 37, name: 'Gardens', tier: 5, upgradesFrom: ['Courtyard'], upgradesTo: ['Wharf', 'Temple'], isUnique: false },
  { id: 38, name: 'Vaal Pyramid', tier: 5, upgradesFrom: ['Barrows', 'Beach'], upgradesTo: ['Canyon'], isUnique: false },
  { id: 39, name: 'City Square', tier: 5, upgradesFrom: ['Beach'], upgradesTo: ['Fields'], isUnique: false },
  { id: 40, name: 'Volcano', tier: 6, upgradesFrom: ['Underground Sea'], upgradesTo: ['Lava Chamber'], isUnique: false },
  { id: 41, name: 'Precinct', tier: 6, upgradesFrom: ['Jungle Valley', 'Mausoleum'], upgradesTo: ['Conservatory', 'Geode'], isUnique: false },
  { id: 42, name: 'Sulphur Vents', tier: 6, upgradesFrom: ['Mausoleum'], upgradesTo: ['Geode'], isUnique: false },
  { id: 43, name: 'Ashen Wood', tier: 6, upgradesFrom: ['Alleyways'], upgradesTo: ['Primordial Pool'], isUnique: false },
  { id: 44, name: 'Academy', tier: 6, upgradesFrom: ['Maze', 'Port'], upgradesTo: ['Underground River'], isUnique: false },
  { id: 45, name: 'Haunted Mansion', tier: 6, upgradesFrom: ['Port'], upgradesTo: ['Underground River', 'Cells'], isUnique: false },
  { id: 46, name: 'Phantasmagoria', tier: 6, upgradesFrom: ['Residence'], upgradesTo: ['Bazaar', 'Arcade'], isUnique: false },
  { id: 47, name: 'Temple', tier: 6, upgradesFrom: ['Residence', 'Gardens'], upgradesTo: ['Toxic Sewer', 'Arcade'], isUnique: false },
  { id: 48, name: 'Wharf', tier: 6, upgradesFrom: ['Gardens'], upgradesTo: ['Toxic Sewer'], isUnique: false },
  { id: 49, name: 'Canyon', tier: 6, upgradesFrom: ['Vaal Pyramid'], upgradesTo: ['Ghetto'], isUnique: false },
  { id: 50, name: 'Fields', tier: 6, upgradesFrom: ['City Square'], upgradesTo: ['Dunes'], isUnique: false },
  { id: 51, name: 'Lava Chamber', tier: 7, upgradesFrom: ['Volcano'], upgradesTo: ['Overgrown Ruin'], isUnique: false },
  { id: 52, name: 'Conservatory', tier: 7, upgradesFrom: ['Precinct'], upgradesTo: ['Sepulchre'], isUnique: false },
  { id: 53, name: 'Geode', tier: 7, upgradesFrom: ['Sulphur Vents'], upgradesTo: ['Mineral Pools'], isUnique: false },
  { id: 54, name: 'Primordial Pool', tier: 7, upgradesFrom: ['Ashen  Wood'], upgradesTo: ['Promenade'], isUnique: false },
  { id: 55, name: 'Underground River', tier: 7, upgradesFrom: ['Academy', 'Haunted Mansion'], upgradesTo: ['Laboratory'], isUnique: false },
  { id: 56, name: 'Cells', tier: 7, upgradesFrom: ['Haunted Mansion'], upgradesTo: ['Laboratory'], isUnique: false },
  { id: 57, name: 'Bazaar', tier: 7, upgradesFrom: ['Phantasmagoria'], upgradesTo: ['Shore', 'Arachnid Nest'], isUnique: false },
  { id: 58, name: 'Arcade', tier: 7, upgradesFrom: ['Phantasmagoria', 'Temple'], upgradesTo: ['Arachnid Nest'], isUnique: false },
  { id: 59, name: 'Toxic Sewer', tier: 7, upgradesFrom: ['Wharf', 'Temple'], upgradesTo: ['Mud Geyser'], isUnique: false },
  { id: 60, name: 'Ghetto', tier: 7, upgradesFrom: ['Canyon'], upgradesTo: ['Wasteland'], isUnique: false },
  { id: 61, name: 'Dunes', tier: 7, upgradesFrom: ['Fields'], upgradesTo: ['Orchard', 'Infested Valley'], isUnique: false },
];

export default maps;
