const maps = [
  { id: 0, name: 'Atoll', tier: 1, upgradesFrom: [], upgradesTo: ['Arid Lake', 'Iceberg'], isUnique: false },
  { id: 1, name: 'Channel', tier: 1, upgradesFrom: [], upgradesTo: ['Armoury', 'Thicket'], isUnique: false },
  { id: 2, name: 'Flooded Mine', tier: 1, upgradesFrom: [], upgradesTo: ['Dungeon'], isUnique: false },
  { id: 3, name: 'Ramparts', tier: 1, upgradesFrom: [], upgradesTo: ['Pen'], isUnique: false },
  { id: 4, name: 'Arid Lake', tier: 2, upgradesFrom: ['Atoll'], upgradesTo: ['Fungal Hollow', 'Grotto'], isUnique: false },
  { id: 5, name: 'Iceberg', tier: 2, upgradesFrom: ['Atoll'], upgradesTo: ['Grotto', 'Cursed Crypt'], isUnique: false },
  { id: 6, name: 'Armoury', tier: 2, upgradesFrom: ['Channel'], upgradesTo: ['Graveyard', 'Excavation'], isUnique: false },
  { id: 7, name: 'Thicket', tier: 2, upgradesFrom: ['Channel'], upgradesTo: ['Desert', 'Excavation'], isUnique: false },
  { id: 8, name: 'Dungeon', tier: 2, upgradesFrom: ['Flooded Mine'], upgradesTo: ['Shipyard', 'Peninsula'], isUnique: false },
  { id: 9, name: 'Pen', tier: 2, upgradesFrom: ['Ramparts'], upgradesTo: ['Bone Crypt', 'Cage'], isUnique: false },
  { id: 10, name: 'Fungal Hollow', tier: 3, upgradesFrom: ['Arid Lake'], upgradesTo: ['Marshes', 'Lighthouse'], isUnique: false },
  { id: 11, name: 'Grotto', tier: 3, upgradesFrom: ['Arid Lake', 'Iceberg'], upgradesTo: ['Lighthouse'], isUnique: false },
  { id: 12, name: 'Cursed Crypt', tier: 3, upgradesFrom: ['Iceberg'], upgradesTo: ['Crater'], isUnique: false },
  { id: 13, name: 'Graveyard', tier: 3, upgradesFrom: ['Armoury'], upgradesTo: ['Glacier'], isUnique: false },
  { id: 14, name: 'Excavation', tier: 3, upgradesFrom: ['Armoury', 'Thicket'], upgradesTo: ['Glacier', 'Strand'], isUnique: false },
  { id: 15, name: 'Desert', tier: 3, upgradesFrom: ['Thicket'], upgradesTo: ['Spider Lair', 'Strand'], isUnique: false },
  { id: 16, name: 'Shipyard', tier: 3, upgradesFrom: ['Dungeon'], upgradesTo: ['Lookout', 'Courtyard'], isUnique: false },
  { id: 17, name: 'Peninsula', tier: 3, upgradesFrom: ['Dungeon'], upgradesTo: ['Courtyard'], isUnique: false },
  { id: 18, name: 'Bone Crypt', tier: 3, upgradesFrom: ['Pen'], upgradesTo: ['Barrows', 'Beach'], isUnique: false },
  { id: 19, name: 'Cage', tier: 3, upgradesFrom: ['Pen'], upgradesTo: ['Beach'], isUnique: false },
  { id: 20, name: 'Marshes', tier: 4, upgradesFrom: ['Fungal Hollow'], upgradesTo: ['Underground Sea', 'Jungle Valley'], isUnique: false },
  { id: 21, name: 'Lighthouse', tier: 4, upgradesFrom: ['Fungal Hollow', 'Grotto'], upgradesTo: ['Jungle Valley'], isUnique: false },
  { id: 22, name: 'Crater', tier: 4, upgradesFrom: ['Cursed Crypt'], upgradesTo: ['Jungle Valley', 'Mausoleum'], isUnique: false },
  { id: 23, name: 'Glacier', tier: 4, upgradesFrom: ['Graveyard', 'Excavation'], upgradesTo: ['Alleyways'], isUnique: false },
  { id: 24, name: 'Strand', tier: 4, upgradesFrom: ['Desert', 'Excavation'], upgradesTo: ['Maze'], isUnique: false },
  { id: 25, name: 'Spider Lair', tier: 4, upgradesFrom: ['Desert'], upgradesTo: ['Maze', 'Port'], isUnique: false },
  { id: 26, name: 'Lookout', tier: 4, upgradesFrom: ['Shipyard'], upgradesTo: ['Residence'], isUnique: false },
  { id: 27, name: 'Courtyard', tier: 4, upgradesFrom: ['Shipyard', 'Peninsula'], upgradesTo: ['Gardens'], isUnique: false },
  { id: 28, name: 'Barrows', tier: 4, upgradesFrom: ['Bone Crypt'], upgradesTo: ['Vaal Pyramid'], isUnique: false },
  { id: 29, name: 'Beach', tier: 4, upgradesFrom: ['Bone Crypt', 'Cage'], upgradesTo: ['Vaal Pyramid', 'City Square'], isUnique: false },
  { id: 30, name: 'Underground Sea', tier: 5, upgradesFrom: ['Marshes'], upgradesTo: ['Volcano'], isUnique: false },
  { id: 31, name: 'Jungle Valley', tier: 5, upgradesFrom: ['Marshes', 'Crater'], upgradesTo: ['Precinct'], isUnique: false },
  { id: 32, name: 'Mausoleum', tier: 5, upgradesFrom: ['Crater'], upgradesTo: ['Precinct', 'Sulphur Vents'], isUnique: false },
  { id: 33, name: 'Alleyways', tier: 5, upgradesFrom: ['Glacier'], upgradesTo: ['Ashen Wood'], isUnique: false },
  { id: 34, name: 'Maze', tier: 5, upgradesFrom: ['Strand', 'Spider Lair'], upgradesTo: ['Academy'], isUnique: false },
  { id: 35, name: 'Port', tier: 5, upgradesFrom: ['Spider Lair'], upgradesTo: ['Academy', 'Haunted Mansion'], isUnique: false },
  { id: 36, name: 'Residence', tier: 5, upgradesFrom: ['Lookout'], upgradesTo: ['Phantasmagoria', 'Temple'], isUnique: false },
  { id: 37, name: 'Gardens', tier: 5, upgradesFrom: ['Courtyard'], upgradesTo: ['Wharf', 'Temple'], isUnique: false },
  { id: 38, name: 'Vaal Pyramid', tier: 5, upgradesFrom: ['Barrows', 'Beach'], upgradesTo: ['Canyon'], isUnique: false },
  { id: 39, name: 'City Square', tier: 5, upgradesFrom: ['Beach'], upgradesTo: ['Fields'], isUnique: false },
  { id: 40, name: 'Volcano', tier: 6, upgradesFrom: ['Underground Sea'], upgradesTo: ['Lava Chamber'], isUnique: false },
  { id: 41, name: 'Precinct', tier: 6, upgradesFrom: ['Jungle Valley', 'Mausoleum'], upgradesTo: ['Conservatory', 'Geode'], isUnique: false },
  { id: 42, name: 'Sulphur Vents', tier: 6, upgradesFrom: ['Mausoleum'], upgradesTo: ['Geode'], isUnique: false },
  { id: 43, name: 'Ashen Wood', tier: 6, upgradesFrom: ['Alleyways'], upgradesTo: ['Primordial Pool'], isUnique: false },
  { id: 44, name: 'Academy', tier: 6, upgradesFrom: ['Maze', 'Port'], upgradesTo: ['Underground River'], isUnique: false },
  { id: 45, name: 'Haunted Mansion', tier: 6, upgradesFrom: ['Port'], upgradesTo: ['Underground River', 'Cells'], isUnique: false },
  { id: 46, name: 'Phantasmagoria', tier: 6, upgradesFrom: ['Residence'], upgradesTo: ['Bazaar', 'Arcade'], isUnique: false },
  { id: 47, name: 'Temple', tier: 6, upgradesFrom: ['Residence', 'Gardens'], upgradesTo: ['Toxic Sewer', 'Arcade'], isUnique: false },
  { id: 48, name: 'Wharf', tier: 6, upgradesFrom: ['Gardens'], upgradesTo: ['Toxic Sewer'], isUnique: false },
  { id: 49, name: 'Canyon', tier: 6, upgradesFrom: ['Vaal Pyramid'], upgradesTo: ['Ghetto'], isUnique: false },
  { id: 50, name: 'Fields', tier: 6, upgradesFrom: ['City Square'], upgradesTo: ['Dunes'], isUnique: false },
  { id: 51, name: 'Lava Chamber', tier: 7, upgradesFrom: ['Volcano'], upgradesTo: ['Overgrown Ruin'], isUnique: false },
  { id: 52, name: 'Conservatory', tier: 7, upgradesFrom: ['Precinct'], upgradesTo: ['Sepulchre'], isUnique: false },
  { id: 53, name: 'Geode', tier: 7, upgradesFrom: ['Sulphur Vents'], upgradesTo: ['Mineral Pools'], isUnique: false },
  { id: 54, name: 'Primordial Pool', tier: 7, upgradesFrom: ['Ashen Wood'], upgradesTo: ['Promenade'], isUnique: false },
  { id: 55, name: 'Underground River', tier: 7, upgradesFrom: ['Academy', 'Haunted Mansion'], upgradesTo: ['Laboratory'], isUnique: false },
  { id: 56, name: 'Cells', tier: 7, upgradesFrom: ['Haunted Mansion'], upgradesTo: ['Laboratory'], isUnique: false },
  { id: 57, name: 'Bazaar', tier: 7, upgradesFrom: ['Phantasmagoria'], upgradesTo: ['Shore', 'Arachnid Nest'], isUnique: false },
  { id: 58, name: 'Arcade', tier: 7, upgradesFrom: ['Phantasmagoria', 'Temple'], upgradesTo: ['Arachnid Nest'], isUnique: false },
  { id: 59, name: 'Toxic Sewer', tier: 7, upgradesFrom: ['Wharf', 'Temple'], upgradesTo: ['Mud Geyser'], isUnique: false },
  { id: 60, name: 'Ghetto', tier: 7, upgradesFrom: ['Canyon'], upgradesTo: ['Wasteland'], isUnique: false },
  { id: 61, name: 'Dunes', tier: 7, upgradesFrom: ['Fields'], upgradesTo: ['Orchard', 'Infested Valley'], isUnique: false },
  { id: 62, name: 'Overgrown Ruin', tier: 8, upgradesFrom: ['Lava Chamber'], upgradesTo: ['Waterways'], isUnique: false },
  { id: 63, name: 'Sepulchre', tier: 8, upgradesFrom: ['Conservatory'], upgradesTo: ['Arena'], isUnique: false },
  { id: 64, name: 'Mineral Pools', tier: 8, upgradesFrom: ['Geode'], upgradesTo: ['Museum'], isUnique: false },
  { id: 65, name: 'Promenade', tier: 8, upgradesFrom: ['Primordial Pool'], upgradesTo: ['Vault'], isUnique: false },
  { id: 66, name: 'Laboratory', tier: 8, upgradesFrom: ['Underground River', 'Cells'], upgradesTo: ['Moon Temple'], isUnique: false },
  { id: 67, name: 'Shore', tier: 8, upgradesFrom: ['Bazaar'], upgradesTo: ['Relic Chambers'], isUnique: false },
  { id: 68, name: 'Arachnid Nest', tier: 8, upgradesFrom: ['Bazaar', 'Arcade'], upgradesTo: ['Ancient City'], isUnique: false },
  { id: 69, name: 'Mud Geyser', tier: 8, upgradesFrom: ['Toxic Sewer'], upgradesTo: ['Scriptorium'], isUnique: false },
  { id: 70, name: 'Wasteland', tier: 8, upgradesFrom: ['Ghetto'], upgradesTo: ['Cemetery'], isUnique: false },
  { id: 71, name: 'Orchard', tier: 8, upgradesFrom: ['Dunes'], upgradesTo: ['Waste Pool'], isUnique: false },
  { id: 72, name: 'Infested Valley', tier: 8, upgradesFrom: ['Dunes'], upgradesTo: ['Tropical Island'], isUnique: false },
  { id: 73, name: 'Waterways', tier: 9, upgradesFrom: ['Overgrown Ruin'], upgradesTo: ['Belfry'], isUnique: false },
  { id: 74, name: 'Arena', tier: 9, upgradesFrom: ['Sepulchre'], upgradesTo: ['Leyline', 'Coral Ruins'], isUnique: false },
  { id: 75, name: 'Museum', tier: 9, upgradesFrom: ['Mineral Pools'], upgradesTo: ['Coral Ruins'], isUnique: false },
  { id: 76, name: 'Vault', tier: 9, upgradesFrom: ['Promenade'], upgradesTo: ['Coves'], isUnique: false },
  { id: 77, name: 'Moon Temple', tier: 9, upgradesFrom: ['Laboratory'], upgradesTo: ['Pit'], isUnique: false },
  { id: 78, name: 'Relic Chambers', tier: 9, upgradesFrom: ['Shore'], upgradesTo: ['Plaza'], isUnique: false },
  { id: 79, name: 'Ancient City', tier: 9, upgradesFrom: ['Arachnid Nest'], upgradesTo: ['Plaza'], isUnique: false },
  { id: 80, name: 'Scriptorium', tier: 9, upgradesFrom: ['Mud Geyser'], upgradesTo: ['Plateau'], isUnique: false },
  { id: 81, name: 'Cemetery', tier: 9, upgradesFrom: ['Wasteland'], upgradesTo: ['Pier'], isUnique: false },
  { id: 82, name: 'Waste Pool', tier: 9, upgradesFrom: ['Orchard'], upgradesTo: ['Pier', 'Spider Forest'], isUnique: false },
  { id: 83, name: 'Tropical Island', tier: 9, upgradesFrom: ['Infested Valley'], upgradesTo: ['Estuary', 'Spider Forest'], isUnique: false },
  { id: 84, name: 'Belfry', tier: 10, upgradesFrom: ['Waterways'], upgradesTo: ['Arachnid Tomb'], isUnique: false },
  { id: 85, name: 'Leyline', tier: 10, upgradesFrom: ['Arena'], upgradesTo: ['Crystal Ore', 'Mesa'], isUnique: false },
  { id: 86, name: 'Coral Ruins', tier: 10, upgradesFrom: ['Arena', 'Museum'], upgradesTo: ['Crystal Ore'], isUnique: false },
  { id: 87, name: 'Coves', tier: 10, upgradesFrom: ['Vault'], upgradesTo: ['Burial Chambers'], isUnique: false },
  { id: 88, name: 'Pit', tier: 10, upgradesFrom: ['Moon Temple'], upgradesTo: ['Park'], isUnique: false },
  { id: 89, name: 'Plaza', tier: 10, upgradesFrom: ['Relic Chambers', 'Ancient City'], upgradesTo: ['Siege'], isUnique: false },
  { id: 90, name: 'Plateau', tier: 10, upgradesFrom: ['Scriptorium'], upgradesTo: ['Bog'], isUnique: false },
  { id: 91, name: 'Pier', tier: 10, upgradesFrom: ['Cemetery', 'Waste Pool'], upgradesTo: ['Factory'], isUnique: false },
  { id: 92, name: 'Spider Forest', tier: 10, upgradesFrom: ['Tropical Island', 'Waste Pool'], upgradesTo: ['Chateau', 'Factory'], isUnique: false },
  { id: 93, name: 'Estuary', tier: 10, upgradesFrom: ['Tropical Island'], upgradesTo: ['Chateau', 'Lair'], isUnique: false },
  { id: 94, name: 'Arachnid Tomb', tier: 11, upgradesFrom: ['Belfry'], upgradesTo: ['Villa'], isUnique: false },
  { id: 95, name: 'Mesa', tier: 11, upgradesFrom: ['Leyline'], upgradesTo: ['Colonnade'], isUnique: false },
  { id: 96, name: 'Crystal Ore', tier: 11, upgradesFrom: ['Leyline', 'Coral Ruins'], upgradesTo: ['Colonnade'], isUnique: false },
  { id: 97, name: 'Burial Chambers', tier: 11, upgradesFrom: ['Coves'], upgradesTo: ['Necropolis'], isUnique: false },
  { id: 98, name: 'Park', tier: 11, upgradesFrom: ['Pit'], upgradesTo: ['Defiled Cathedral'], isUnique: false },
  { id: 99, name: 'Siege', tier: 11, upgradesFrom: ['Plaza'], upgradesTo: ['Malformation'], isUnique: false },
  { id: 100, name: 'Bog', tier: 11, upgradesFrom: ['Plateau'], upgradesTo: ['Arsenal', 'Overgrown Shrine'], isUnique: false },
  { id: 101, name: 'Factory', tier: 11, upgradesFrom: ['Pier', 'Spider Forest'], upgradesTo: ['Ivory Temple'], isUnique: false },
  { id: 102, name: 'Chateau', tier: 11, upgradesFrom: ['Estuary', 'Spider Forest'], upgradesTo: ['Castle Ruins'], isUnique: false },
  { id: 103, name: 'Lair', tier: 11, upgradesFrom: ['Estuary'], upgradesTo: ['Castle Ruins'], isUnique: false },
  { id: 104, name: 'Villa', tier: 12, upgradesFrom: ['Arachnid Tomb'], upgradesTo: ['Acid Caverns', 'Reef'], isUnique: false },
  { id: 105, name: 'Colonnade', tier: 12, upgradesFrom: ['Crystal Ore', 'Mesa'], upgradesTo: ['Core'], isUnique: false },
  { id: 106, name: 'Necropolis', tier: 12, upgradesFrom: ['Burial Chambers'], upgradesTo: ['Racecourse'], isUnique: false },
  { id: 107, name: 'Defiled Cathedral', tier: 12, upgradesFrom: ['Park'], upgradesTo: ['Caldera'], isUnique: false },
  { id: 108, name: 'Malformation', tier: 12, upgradesFrom: ['Siege'], upgradesTo: ['Colosseum'], isUnique: false },
  { id: 109, name: 'Arsenal', tier: 12, upgradesFrom: ['Bog'], upgradesTo: ['Shrine'], isUnique: false },
  { id: 110, name: 'Overgrown Shrine', tier: 12, upgradesFrom: ['Bog'], upgradesTo: ['Shrine'], isUnique: false },
  { id: 111, name: 'Ivory Temple', tier: 12, upgradesFrom: ['Factory'], upgradesTo: ['Dig'], isUnique: false },
  { id: 112, name: 'Castle Ruins', tier: 12, upgradesFrom: ['Chateau', 'Lair'], upgradesTo: ['Crimson Temple'], isUnique: false },
  { id: 113, name: 'Acid Caverns', tier: 13, upgradesFrom: ['Villa'], upgradesTo: ['Dark Forest'], isUnique: false },
  { id: 114, name: 'Reef', tier: 13, upgradesFrom: ['Villa'], upgradesTo: ['Dark Forest'], isUnique: false },
  { id: 115, name: 'Core', tier: 13, upgradesFrom: ['Colonnade'], upgradesTo: ['Dark Forest'], isUnique: false },
  { id: 116, name: 'Racecourse', tier: 13, upgradesFrom: ['Necropolis'], upgradesTo: ['Palace'], isUnique: false },
  { id: 117, name: 'Caldera', tier: 13, upgradesFrom: ['Defiled Cathedral'], upgradesTo: ['Basilica', 'Sunken City'], isUnique: false },
  { id: 118, name: 'Colosseum', tier: 13, upgradesFrom: ['Malformation'], upgradesTo: ['Courthouse'], isUnique: false },
  { id: 119, name: 'Shrine', tier: 13, upgradesFrom: ['Arsenal'], upgradesTo: ['Courthouse', 'Carcass'], isUnique: false },
  { id: 120, name: 'Dig', tier: 13, upgradesFrom: ['Ivory Temple'], upgradesTo: ['Terrace'], isUnique: false },
  { id: 121, name: 'Crimson Temple', tier: 13, upgradesFrom: ['Castle Ruins'], upgradesTo: ['Terrace'], isUnique: false },
  { id: 122, name: 'Dark Forest', tier: 14, upgradesFrom: ['Acid Caverns', 'Reef', 'Core'], upgradesTo: ['Tower'], isUnique: false },
  { id: 123, name: 'Palace', tier: 14, upgradesFrom: ['Racecourse'], upgradesTo: ['Desert Spring'], isUnique: false },
  { id: 124, name: 'Sunken City', tier: 14, upgradesFrom: ['Caldera'], upgradesTo: ['Lava Lake'], isUnique: false },
  { id: 125, name: 'Basilica', tier: 14, upgradesFrom: ['Caldera'], upgradesTo: ['Lava Lake'], isUnique: false },
  { id: 126, name: 'Courthouse', tier: 14, upgradesFrom: ['Colosseum', 'Shrine'], upgradesTo: ['Primordial Blocks'], isUnique: false },
  { id: 127, name: 'Carcass', tier: 14, upgradesFrom: ['Shrine'], upgradesTo: ['Primordial Blocks'], isUnique: false },
  { id: 128, name: 'Terrace', tier: 14, upgradesFrom: ['Crimson Temple', 'Dig'], upgradesTo: ['Summit'], isUnique: false },
  { id: 129, name: 'Tower', tier: 15, upgradesFrom: ['Dark Forest'], upgradesTo: ['Lair of the Hydra'], isUnique: false },
  { id: 130, name: 'Desert Spring', tier: 15, upgradesFrom: ['Palace'], upgradesTo: ['Pit of the Chimera'], isUnique: false },
  { id: 131, name: 'Lava Lake', tier: 15, upgradesFrom: ['Palace', 'Basilica', 'Sunken City'], upgradesTo: ['Pit of the Chimera'], isUnique: false },
  { id: 132, name: 'Primordial Blocks', tier: 15, upgradesFrom: ['Carcass', 'Courthouse'], upgradesTo: ['Maze of the Minotaur'], isUnique: false },
  { id: 133, name: 'Summit', tier: 15, upgradesFrom: ['Crimson Temple', 'Dig'], upgradesTo: ['Forge of the Phoenix'], isUnique: false },
  { id: 134, name: 'Lair of the Hydra', tier: 16, upgradesFrom: ['Tower'], upgradesTo: ['The Shaper\'s Realm'], isUnique: false },
  { id: 135, name: 'Pit of the Chimera', tier: 16, upgradesFrom: ['Desert Spring', 'Lava Lake'], upgradesTo: ['The Shaper\'s Realm'], isUnique: false },
  { id: 136, name: 'Maze of the Minotaur', tier: 16, upgradesFrom: ['Primordial Blocks'], upgradesTo: ['The Shaper\'s Realm'], isUnique: false },
  { id: 137, name: 'Forge of the Phoenix', tier: 16, upgradesFrom: ['Summit'], upgradesTo: ['The Shaper\'s Realm'], isUnique: false },
  { id: 138, name: 'The Shaper\'s Realm', tier: 17, upgradesFrom: ['Lair of the Hydra', 'Pit of the Chimera', 'Maze of the Minotaur', 'Forge of the Phoenix'], upgradesTo: [''], isUnique: false },
  { id: 139, name: 'Vaal Temple', tier: 16, upgradesFrom: ['T15 map + Vaal Orb'], upgradesTo: [], isUnique: false },
];

export default maps;
